spring:
  profile: live
server:
  port: 30000
---
spring:
  profiles: dev
server:
  port: 30001
kafka:
  -
    clusters:
      name: crispy
      clusterId: abcde
      boostrapServers:
        - localhost:9092

